name: halfmarathon-predictor
region: fra

services:
- name: web
  github:
    repo: TWOJA_NAZWA_UŻYTKOWNIKA/halfmarathon-predictor  # ← ZMIEŃ TO!
    branch: main
    deploy_on_push: true
  
  dockerfile_path: Dockerfile
  
  http_port: 8080
  
  instance_count: 1
  instance_size_slug: basic-xs  # ← ZWIĘKSZONE z basic-xxs (512MB → 1GB RAM)
  
  envs:
  # Digital Ocean Spaces (WYMAGANE)
  - key: DO_SPACES_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DO_SPACES_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: DO_SPACES_REGION
    value: fra1
    scope: RUN_TIME
  - key: DO_SPACES_BUCKET
    value: halfmarathon-ml
    scope: RUN_TIME
  
  # OpenAI (WYMAGANE)
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: OPENAI_MODEL
    value: gpt-4o-mini
    scope: RUN_TIME
  
  # Langfuse (OPCJONALNE - usuń jeśli nie używasz)
  - key: LANGFUSE_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: LANGFUSE_PUBLIC_KEY
    scope: RUN_TIME
    type: SECRET
  - key: LANGFUSE_HOST
    value: https://cloud.langfuse.com
    scope: RUN_TIME
  
  health_check:
    http_path: /_stcore/health
    initial_delay_seconds: 120  # ← ZWIĘKSZONE z 60
    period_seconds: 15           # ← ZWIĘKSZONE z 10
    timeout_seconds: 10          # ← ZWIĘKSZONE z 5
    success_threshold: 1
    failure_threshold: 5         # ← ZWIĘKSZONE z 3