[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
# 🔹 Lokalny adres, bez headless — otworzy przeglądarkę automatycznie
headless = false
address = "localhost"
port = 8080
enableXsrfProtection = true
# enableCORS NIE ustawiamy – domyślnie true, bez konfliktu

[browser]
# 🔹 Wyłącza telemetrykę Streamlit
gatherUsageStats = false
# 🔹 Jawne wskazanie adresu dla przeglądarki
serverAddress = "localhost"
serverPort = 8080
