[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# NOTE: Do not set address/port in production. Procfile uses $PORT.
[server]
# LOCAL CONFIG - dla development na Windows/Mac/Linux
headless = true
address = "localhost"  # ← ZMIANA z 0.0.0.0 na localhost
port = 8501              # ← ZMIANA z 8080 na 8501 (standardowy Streamlit)
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = true
runOnSave = false
fileWatcherType = "none"
maxUploadSize = 50

[browser]
gatherUsageStats = false
serverAddress = "localhost"  # ← ZMIANA
serverPort = 8501            # ← ZMIANA

[runner]
magicEnabled = false
fastReruns = true
enforceSerializableSessionState = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
showErrorDetails = true
toolbarMode = "minimal"