[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = false          # ← false dla local
address = "localhost"     # ← localhost zamiast 0.0.0.0
port = 8501              # ← 8501 zamiast 8080
enableXsrfProtection = false  # ← false dla local
enableCORS = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501