[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
# PRODUCTION CONFIG - zoptymalizowane dla Digital Ocean
headless = true
address = "0.0.0.0"
port = 8080
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = true
runOnSave = false
fileWatcherType = "none"
maxUploadSize = 50

# Health check endpoint
baseUrlPath = ""

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8080

[runner]
# Prevent memory issues
magicEnabled = false
fastReruns = true
enforceSerializableSessionState = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
# Timeout settings
showErrorDetails = true
toolbarMode = "minimal"